compilers:
- compiler:
    spec: gcc@=12.3.0
    paths:
      cc: /usr/bin/gcc-12
      cxx: /usr/bin/g++-12
      f77: /usr/bin/gfortran-12
      fc: /usr/bin/gfortran-12
    flags: {}
    operating_system: sles15
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=13.3.0
    paths:
      cc: /usr/bin/gcc-13
      cxx: /usr/bin/g++-13
      f77: /usr/bin/gfortran-13
      fc: /usr/bin/gfortran-13
    flags: {}
    operating_system: sles15
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=14.2.0
    paths:
      cc: /usr/bin/gcc-14
      cxx: /usr/bin/g++-14
      f77: /usr/bin/gfortran-14
      fc: /usr/bin/gfortran-14
    flags: {}
    operating_system: sles15
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []

- compiler:
    spec: cce@=18.0.0
    paths:
      cc: /opt/cray/pe/cce/18.0.0/bin/craycc
      cxx: /opt/cray/pe/cce/18.0.0/bin/craycxx
      f77: /opt/cray/pe/cce/18.0.0/bin/crayftn
      fc: /opt/cray/pe/cce/18.0.0/bin/crayftn
    flags: {}
    operating_system: sles15
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: cce@=19.0.0
    paths:
      cc: /opt/cray/pe/cce/19.0.0/bin/craycc
      cxx: /opt/cray/pe/cce/19.0.0/bin/craycxx
      f77: /opt/cray/pe/cce/19.0.0/bin/crayftn
      fc: /opt/cray/pe/cce/19.0.0/bin/crayftn
    flags: {}
    operating_system: sles15
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []

- compiler:
    spec: nvhpc@24.11
    paths:
      cc: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers/bin/nvc
      cxx: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers/bin/nvc++
      f77: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers/bin/nvfortran
      fc: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers/bin/nvfortran
    flags: {}
    operating_system: sles15
    target: any
    modules: []
    extra_rpaths: []

